
// You may only use fgets() to pull input from stdin
// You may use any print function to stdout to print 
// out chat messages
#include <stdio.h>

// You may use memory allocators and helper functions 
// (e.g., rand()).  You may not use system().
#include <stdlib.h>

#include <inttypes.h>
#include <time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/mman.h>

#ifndef UTIL_H_
#define UTIL_H_

#define ADDR_PTR uint64_t 
#define CYCLES volatile uint32_t
#define CACHE_LINE_SIZE 64
#define TIME_CUTOFF 100 
#define TIME_SLOT 2500 

CYCLES measure_one_block_access_time(ADDR_PTR addr);
void flush_one_block(ADDR_PTR addr);
CYCLES get_highres_time();
void wait_for_time(CYCLES time);
// operation padding for send_bit function calls (used to ensure cache line sized functions)
#define NOP_PADDING			\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	\
	asm __volatile__ ("nop");	

#endif
